# SPDX-FileCopyrightText: 2026 Alexandr Savca <alexandr.savca89@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

format: zeppe-lin.recipe/1
package:
  name: acl
  version: 2.4.0
  release: 1
  summary: Access Control List filesystem support
  homepage: https://savannah.nongnu.org/projects/acl/
  licenses:
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
requirements:
  build:
    - package: attr
sources:
  - url: https://download.savannah.gnu.org/releases/acl/acl-2.4.0.tar.gz
    name: acl-2.4.0.tar.gz
    sha256: 73c853c3d44e1f693e5a96a986f1bd19d3d0dac2c7d453e796177774bc4e5f6a
build:
  language: posix-shell
  script: |
    set -eu

    attr="$PKG_BUILD_INPUT_ROOT/attr"
    export CPPFLAGS="-I$attr/usr/include"
    export LDFLAGS="-L$attr/usr/lib -Wl,-rpath-link,$attr/usr/lib"
    export LD_LIBRARY_PATH="$attr/usr/lib"
    export PKG_CONFIG_PATH="$attr/usr/lib/pkgconfig"

    tar --no-same-owner --no-same-permissions -xf "$PKG_SOURCE_ROOT/acl-2.4.0.tar.gz"
    mkdir build
    cd build

    ../acl-2.4.0/configure \
      --prefix=/usr \
      --bindir=/usr/bin \
      --disable-nls

    make V=1
    make DESTDIR="$PKG_DESTDIR" install

    rm -rf "$PKG_DESTDIR/usr/share/doc"
