# SPDX-FileCopyrightText: 2026 Alexandr Savca <alexandr.savca89@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

format: zeppe-lin.recipe/1
package:
  name: scdoc
  version: 1.11.5
  release: 1
  summary: Simple man page generator for POSIX systems
  homepage: https://sr.ht/~sircmpwn/scdoc/
  licenses:
    - MIT
requirements: {}
sources:
  - url: https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.5.tar.gz
    name: scdoc-1.11.5.tar.gz
    sha256: 98780bbdf16c1bce89ef3a8c0f537ac6e4ea77087b609e7698857614488a2a62
build:
  language: posix-shell
  script: |
    set -eu

    tar -xf "$PKG_SOURCE_ROOT/scdoc-1.11.5.tar.gz"
    cd scdoc-1.11.5

    make CC="${CC:-cc}" PREFIX=/usr DESTDIR="$PKG_DESTDIR" install
