# SPDX-FileCopyrightText: 2026 Alexandr Savca <alexandr.savca89@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

format: zeppe-lin.recipe/1
package:
  name: lz4
  version: 1.10.0
  release: 1
  summary: Extremely fast lossless compression algorithm
  homepage: https://lz4.org/
  licenses:
    - BSD-2-Clause
    - GPL-2.0-or-later
requirements: {}
sources:
  - url: https://github.com/lz4/lz4/releases/download/v1.10.0/lz4-1.10.0.tar.gz
    name: lz4-1.10.0.tar.gz
    unpack: archive
    sha256: 537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b
build:
  language: posix-shell
  script: |
    set -eu

    cd lz4-1.10.0

    CFLAGS=$(printf '%s\n' "${CFLAGS:-}" | sed 's/-O. //')
    export CFLAGS

    make -C lib -j "$PKG_JOBS" V=1 PREFIX=/usr
    make -C programs -j "$PKG_JOBS" V=1 PREFIX=/usr lz4 lz4c
    make PREFIX=/usr DESTDIR="$PKG_DESTDIR" install
